//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPassBook.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMaster
    {
        public CompanyMaster()
        {
            this.BenificiaryMasters = new HashSet<BenificiaryMaster>();
            this.Comments = new HashSet<Comment>();
            this.InstallmentRejections = new HashSet<InstallmentRejection>();
            this.GeoTaggingDetails = new HashSet<GeoTaggingDetail>();
            this.InstallmentDetails = new HashSet<InstallmentDetail>();
            this.InstallmentSignings = new HashSet<InstallmentSigning>();
            this.UserMasters = new HashSet<UserMaster>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string OwnerName { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> Modifiedby { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<BenificiaryMaster> BenificiaryMasters { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<InstallmentRejection> InstallmentRejections { get; set; }
        public virtual ICollection<GeoTaggingDetail> GeoTaggingDetails { get; set; }
        public virtual ICollection<InstallmentDetail> InstallmentDetails { get; set; }
        public virtual ICollection<InstallmentSigning> InstallmentSignings { get; set; }
        public virtual ICollection<UserMaster> UserMasters { get; set; }
    }
}
