//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPassBook.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMaster
    {
        public RoleMaster()
        {
            this.Comments = new HashSet<Comment>();
            this.InstallmentSignings = new HashSet<InstallmentSigning>();
            this.StageInRoles = new HashSet<StageInRole>();
            this.UserInRoles = new HashSet<UserInRole>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<InstallmentSigning> InstallmentSignings { get; set; }
        public virtual ICollection<StageInRole> StageInRoles { get; set; }
        public virtual ICollection<UserInRole> UserInRoles { get; set; }
    }
}
