//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPassBook.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowStage
    {
        public WorkflowStage()
        {
            this.StageInRoles = new HashSet<StageInRole>();
        }
    
        public int StageId { get; set; }
        public string Stage { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<StageInRole> StageInRoles { get; set; }
    }
}
